INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (1,'Aguacate','Bacon',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (2,'Aguacate','Carmen',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (3,'Aguacate','Ettinguer',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (4,'Aguacate','Fuerte',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (5,'Aguacate','Hass',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (6,'Aguacate','Lamb Hass',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (7,'Aguacate','Pinkerton',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (8,'Aguacate','Reed',true);
INSERT IGNORE INTO fertidb.cultivo_sembrado (`cul_codigo`,`cul_nombre`,`cul_variedad`,`cul_estado`) VALUES (9,'Aguacate','Zutano',true);
INSERT IGNORE INTO fertidb.rol (`rol_codigo`,`rol_nombre`,`rol_estado`) VALUES (1,'Administrador',true);
INSERT IGNORE INTO fertidb.rol (`rol_codigo`,`rol_nombre`,`rol_estado`) VALUES (2,'Productor',true);
INSERT IGNORE INTO fertidb.rol (`rol_codigo`,`rol_nombre`,`rol_estado`) VALUES (3,'Almacenista',true);
