MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (1,'Aguacate','Bacon',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (2,'Aguacate','Carmen',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (3,'Aguacate','Ettinguer',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (4,'Aguacate','Fuerte',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (5,'Aguacate','Hass',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (6,'Aguacate','Lamb Hass',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (7,'Aguacate','Pinkerton',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (8,'Aguacate','Reed',true);
MERGE INTO tipo_cultivo (`tc_codigo`,`tc_nombre`,`tc_variedad`,`tc_estado`) VALUES (9,'Aguacate','Zutano',true);
MERGE INTO rol (`rol_codigo`,`rol_nombre`,`rol_estado`) VALUES (1,'Administrador',true);
MERGE INTO rol (`rol_codigo`,`rol_nombre`,`rol_estado`) VALUES (2,'Productor',true);
MERGE INTO rol (`rol_codigo`,`rol_nombre`,`rol_estado`) VALUES (3,'Almacenista',true);