Merge INTO unidad(`uni_codigo`, `uni_nombre`) VALUES (1,'ppm');
Merge INTO unidad(`uni_codigo`, `uni_nombre`) VALUES (2,'cmol/kg');
Merge INTO unidad(`uni_codigo`, `uni_nombre`) VALUES (3,'kg/ha');
MERGE INTO elementos VALUES (1, 'Nitr�geno', 14.006, 5); 
MERGE INTO elementos VALUES (2, 'F�sforo', 30.973, 5);
MERGE INTO elementos VALUES (3, 'Potasio', 39.102, 1);
MERGE INTO elementos VALUES (4, 'Calcio', 40.08, 2);
MERGE INTO elementos VALUES (5, 'Magnesio', 24.312, 2);
MERGE INTO elementos VALUES (6, 'Azufre', 32.064, 6);
MERGE INTO elementos VALUES (7, 'Boro', 10.811, 3);
MERGE INTO elementos VALUES (8, 'Cobre', 63.54, 1);
MERGE INTO elementos VALUES (9, 'Hierro', 55.847, 3);
MERGE INTO elementos VALUES (10, 'Manganeso', 54.938, 3);
MERGE INTO elementos VALUES (11, 'Molibdeno', 95.94, 6);
MERGE INTO elementos VALUES (12, 'Zinc', 65.37, 2);
MERGE INTO rol (`rol_codigo`,`rol_nombre`,`rol_estado`, `rol_tipo`) VALUES (1,'Administrador',true, 'ROLE_ADMIN');
MERGE INTO rol (`rol_codigo`,`rol_nombre`,`rol_estado`, `rol_tipo`) VALUES (2,'Productor',true, 'ROLE_USER');
MERGE INTO rol (`rol_codigo`,`rol_nombre`,`rol_estado`, `rol_tipo`) VALUES (3,'Almacenista',true, 'ROLE_USER');
MERGE INTO Usuario_Seguridad (`id_usuario`, `nombre_usuario`,`password`,`estado`,`codigorol`) VALUES(1, 'Administrador', '$2a$10$OErv.iLt03pww2NcIyTgWu3kmUc5mapfOzrNTdEae9KKFfYOw.Kqa', true, 1);
MERGE INTO Usuario_Seguridad (`id_usuario`, `nombre_usuario`,`password`,`estado`,`codigorol`) VALUES(2, 1047969124, '$2a$10$Hn49HhvxMX.NWuyQM5iJ6.511X/g6f0fL0R3GJ4Wv0hrbn5J8ExQ.', true, 2);
